server:
  port: 8080 # server port

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/firstDB # db Url
      username: root # db username
      password: rootroot #db password
    url: jdbc:mysql://localhost:3306/db

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update