server:
  port: 8080 # server port

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/firstDB
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
